"""
Excel Service
Generates styled Excel workbooks (.xlsx) with custom formatting, multi-tab sheets,
live Excel formulas (SUM, AVERAGE, CAGR), auto column sizing, and native Excel charts.
"""

import os
import json
import logging
from typing import Dict, Any, List, Optional

logger = logging.getLogger(__name__)


def create_excel_workbook(spec: Dict[str, Any], output_path: str) -> Dict[str, Any]:
    """
    Build a styled Excel workbook (.xlsx) from a JSON specification.
    
    Spec format:
    {
        "title": "Financial Forecast 2026",
        "theme_color": "1E3A8A",  # Header color hex
        "sheets": [
            {
                "name": "Revenue Forecast",
                "headers": ["Quarter", "Users", "ARPU", "Revenue"],
                "data": [
                    ["Q1 2026", 10000, "$15.00", "=B2*C2"],
                    ["Q2 2026", 15000, "$16.50", "=B3*C3"],
                    ["Total", "=SUM(B2:B3)", "", "=SUM(D2:D3)"]
                ],
                "chart": {
                    "type": "column", # column, line, bar, pie
                    "title": "Quarterly Revenue Growth",
                    "x_col": 0,
                    "y_col": 3
                }
            }
        ]
    }
    """
    try:
        import openpyxl
        from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
        from openpyxl.utils import get_column_letter
        from openpyxl.chart import BarChart, LineChart, PieChart, Reference

        wb = openpyxl.Workbook()
        # Remove default sheet
        wb.remove(wb.active)

        # Parse theme header fill
        hex_color = spec.get("theme_color", "0F172A").lstrip('#')
        header_fill = PatternFill(start_color=hex_color, end_color=hex_color, fill_type="solid")
        header_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
        title_font = Font(name="Calibri", size=16, bold=True, color=hex_color)
        sub_font = Font(name="Calibri", size=10, italic=True, color="64748B")
        regular_font = Font(name="Calibri", size=11, color="1E293B")
        bold_font = Font(name="Calibri", size=11, bold=True, color="1E293B")

        thin_side = Side(border_style="thin", color="CBD5E1")
        thin_border = Border(left=thin_side, right=thin_side, top=thin_side, bottom=thin_side)
        top_thick_bottom_double = Border(top=Side(border_style="thin", color="0F172A"), bottom=Side(border_style="double", color="0F172A"))

        sheets_data = spec.get("sheets", [])

        if not sheets_data:
            sheets_data = [{
                "name": "Sheet1",
                "headers": spec.get("headers", ["Item", "Value"]),
                "data": spec.get("data", [["Sample", 100]])
            }]

        for sheet_spec in sheets_data:
            sheet_name = sheet_spec.get("name", "Sheet")[:31]  # Excel max 31 chars
            ws = wb.create_sheet(title=sheet_name)
            ws.views.sheetView[0].showGridLines = True

            current_row = 1

            # Title Header in Sheet
            title = sheet_spec.get("title", sheet_name)
            ws.cell(row=current_row, column=1, value=title).font = title_font
            current_row += 1

            subtitle = sheet_spec.get("subtitle", "Generated by Business Agent AI")
            ws.cell(row=current_row, column=1, value=subtitle).font = sub_font
            current_row += 2

            headers = sheet_spec.get("headers", [])
            data_rows = sheet_spec.get("data", [])

            # Write Headers
            if headers:
                for col_idx, h in enumerate(headers, 1):
                    cell = ws.cell(row=current_row, column=col_idx, value=str(h))
                    cell.fill = header_fill
                    cell.font = header_font
                    cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
                    cell.border = thin_border
                ws.row_dimensions[current_row].height = 28
                header_row_idx = current_row
                current_row += 1

            # Write Data Rows
            start_data_row = current_row
            for r_idx, row in enumerate(data_rows):
                is_total_row = any(str(cell_val).strip().lower() in ("total", "totals", "summary", "average") for cell_val in row)
                
                for c_idx, val in enumerate(row, 1):
                    cell = ws.cell(row=current_row, column=c_idx)
                    
                    # Convert formulas and values
                    if isinstance(val, str) and val.startswith("="):
                        cell.value = val
                    elif isinstance(val, (int, float)):
                        cell.value = val
                    else:
                        cell.value = str(val)

                    # Cell Styling
                    if is_total_row:
                        cell.font = bold_font
                        cell.border = top_thick_bottom_double
                    else:
                        cell.font = regular_font
                        cell.border = thin_border

                    # Alignments & Number formatting
                    if isinstance(cell.value, (int, float)):
                        cell.alignment = Alignment(horizontal="right", vertical="center")
                        cell.number_format = '#,##0.00'
                    elif isinstance(val, str) and (val.startswith("$") or "€" in val):
                        cell.alignment = Alignment(horizontal="right", vertical="center")
                    else:
                        cell.alignment = Alignment(horizontal="left", vertical="center")

                ws.row_dimensions[current_row].height = 20
                current_row += 1

            end_data_row = current_row - 1

            # Auto Column Width Adjustment
            for col in ws.columns:
                max_len = 0
                col_letter = get_column_letter(col[0].column)
                for cell in col:
                    if cell.row >= header_row_idx:
                        val_str = str(cell.value or "")
                        if len(val_str) > max_len:
                            max_len = len(val_str)
                ws.column_dimensions[col_letter].width = max(max_len + 4, 12)

            # Native Excel Chart
            chart_spec = sheet_spec.get("chart")
            if chart_spec and headers and data_rows:
                try:
                    chart_type = chart_spec.get("type", "column").lower()
                    chart_title = chart_spec.get("title", f"{sheet_name} Chart")

                    if chart_type in ("column", "bar"):
                        chart = BarChart()
                        chart.type = "col" if chart_type == "column" else "bar"
                    elif chart_type == "line":
                        chart = LineChart()
                    elif chart_type == "pie":
                        chart = PieChart()
                    else:
                        chart = BarChart()

                    chart.title = chart_title
                    chart.style = 10
                    chart.width = 16
                    chart.height = 10

                    data_ref = Reference(ws, min_col=2, min_row=header_row_idx, max_col=len(headers), max_row=end_data_row)
                    cats_ref = Reference(ws, min_col=1, min_row=header_row_idx+1, max_row=end_data_row)

                    chart.add_data(data_ref, titles_from_data=True)
                    chart.set_categories(cats_ref)

                    ws.add_chart(chart, f"A{end_data_row + 3}")
                except Exception as ce:
                    logger.warning("Could not add chart to sheet '%s': %s", sheet_name, ce)

        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        wb.save(output_path)

        return {
            "status": "success",
            "file_path": output_path,
            "sheets_count": len(sheets_data),
            "message": f"Successfully created Excel workbook at '{output_path}'"
        }
    except ImportError:
        logger.warning("openpyxl is not installed.")
        return {
            "status": "error",
            "error": "openpyxl library is not installed. Install via pip install openpyxl."
        }
    except Exception as e:
        logger.error("Error creating Excel workbook: %s", e)
        return {
            "status": "error",
            "error": str(e)
        }


def read_excel_workbook(file_path: str) -> Dict[str, Any]:
    """Read sheets and data from an Excel workbook (.xlsx)."""
    try:
        import openpyxl

        if not os.path.exists(file_path):
            return {"status": "error", "error": f"File does not exist: {file_path}"}

        wb = openpyxl.load_workbook(file_path, data_only=True)
        result_sheets = {}

        for sheet_name in wb.sheetnames:
            ws = wb[sheet_name]
            rows = []
            for row in ws.iter_rows(values_only=True):
                if any(cell is not None for cell in row):
                    rows.append([str(c) if c is not None else "" for c in row])
            result_sheets[sheet_name] = rows

        return {
            "status": "success",
            "file_path": file_path,
            "sheet_names": wb.sheetnames,
            "sheets": result_sheets
        }
    except Exception as e:
        return {"status": "error", "error": str(e)}
